services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 5@_password
      ACCEPT_EULA: Y

