services:
  realm:
    image: mangos/realmserver
    container_name: realmserver
    depends_on:
      - mysql
    ports:
      - 3724:3724
    build:
      context: ..
      dockerfile: ./dev/RealmServer.Dockerfile
    networks:
      - mangosSharp

  game:
    image: mangos/gameserver
    container_name: gameserver
    depends_on:
      - mysql
    ports:
      - 8085:8085
    build:
      context: ..
      dockerfile: ./dev/GameServer.Dockerfile
    networks:
      - mangosSharp

  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mangosSharp:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
    networks:
      - mangosSharp

volumes:
  mangosSharp:
    name: MangosSharp

networks:
  mangosSharp:
